language: ruby
sudo: false
rvm: 2.4.2

matrix:
  include:
    - env: "RAILS_VERION=5.1.4"
    - rvm: 2.3.5
      env: "BLACKLIGHT_VERSION=5.17.2 RAILS_VERSION=5.0.6"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - BLACKLIGHT_VERSION=6.12.0
before_install:
  - gem update --system

jdk: oraclejdk8
