version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
executors:
  ruby_fcrepo_solr:
    parameters:
      ruby_version:
        type: string
      solr_port:
        type: string
        default: '8985'
      fcrepo_version:
        type: string
        default: '4.7'
      solr_version:
        type: string
        default: '7'

    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>-node-browsers-legacy
      - image: ualbertalib/docker-fcrepo4:<< parameters.fcrepo_version>>
        environment:
          CATALINA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
      - image: solr:<< parameters.solr_version >>-alpine
        command: bin/solr -cloud -noprompt -f -p <<parameters.solr_port>>

jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
      solr_port:
        type: string
        default: '8985'
      active_fedora_version:
        type: string
        default: '>0'
      fcrepo_version:
        type: string
        default: '4.7'
      solr_version:
        type: string
        default: '7'
      solr_config_path:
        type: string
        default: '.internal_test_app/solr/conf'

    executor:
      name: 'ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
      solr_port: << parameters.solr_port >>
      solr_version: << parameters.solr_version >>

    working_directory: ~/project

    environment:
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-coffee --skip-puma --skip-test
      RAILS_VERSION: << parameters.rails_version >>
      SOLR_TEST_PORT: << parameters.solr_port >>
      ACTIVE_FEDORA_VERSION: << parameters.active_fedora_version >>
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      RAILS_ENV: test
      RACK_ENV: test
      FCREPO_TEST_PORT: 8080/fcrepo
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress

    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-head

      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "hydra-head.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "hydra-core/lib/generators/hydra/head_generator.rb" }}-<< parameters.active_fedora_version >>-<< parameters.rails_version >>-<< parameters.ruby_version >>

      - samvera/install_solr_core:
          solr_config_path: << parameters.solr_config_path >>

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-head

      - run: bundle exec rake spec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: "ruby2-6_rails5.2"
          ruby_version: 2.6.3
          rails_version: 5.2.3
      - bundle_and_test:
          name: "ruby2-6_rails5.1"
          ruby_version: 2.6.3
          rails_version: 5.1.7
      - bundle_and_test:
          name: "ruby2-6_rails5.1_AF11"
          ruby_version: 2.6.3
          rails_version: 5.1.7
          active_fedora_version: '~>11.5'
          solr_config_path: '.internal_test_app/solr/config'
      - bundle_and_test:
          name: "ruby2-6_rails5.0_AF10"
          ruby_version: 2.6.3
          rails_version: 5.0.7.2
          active_fedora_version: '~>10.3'
          solr_config_path: '.internal_test_app/solr/config'
          solr_version: '6'
      - bundle_and_test:
          name: "ruby2-5_rails5.2"
          ruby_version: 2.5.5
          rails_version: 5.2.3
      - bundle_and_test:
          name: "ruby2-5_rails5.1"
          ruby_version: 2.5.5
          rails_version: 5.1.7
      - bundle_and_test:
          name: "ruby2-5_rails5.1_AF11"
          ruby_version: 2.5.5
          rails_version: 5.1.7
          active_fedora_version: '~>11.5'
          solr_config_path: '.internal_test_app/solr/config'
      - bundle_and_test:
          name: "ruby2-5_rails5.0_AF10"
          ruby_version: 2.5.5
          rails_version: 5.0.7.2
          active_fedora_version: '~>10.3'
          solr_config_path: '.internal_test_app/solr/config'
          solr_version: '6'
      - bundle_and_test:
          name: "ruby2-4_rails5.2"
          ruby_version: 2.4.6
          rails_version: 5.2.3
      - bundle_and_test:
          name: "ruby2-4_rails5.1"
          ruby_version: 2.4.6
          rails_version: 5.1.7
      - bundle_and_test:
          name: "ruby2-4_rails5.1_AF11"
          ruby_version: 2.4.6
          rails_version: 5.1.7
          active_fedora_version: '~>11.5'
          solr_config_path: '.internal_test_app/solr/config'
      - bundle_and_test:
          name: "ruby2-4_rails5.0_AF10"
          ruby_version: 2.4.6
          rails_version: 5.0.7.2
          active_fedora_version: '~>10.3'
          solr_config_path: '.internal_test_app/solr/config'
          solr_version: '6'
